### ISSUE TITLE
rootDir definition in external config file

### ISSUE THREAD

**Issue by francescodisciascio** [snimavat/grails-elfinder-connector#2]
I want to define the grails.plugin.elfinder.rootDir path in an external config file.
I have developed my Grails application, and I've installed the elfinder plugin and the connector.
I've used the following in Config.groovy:

```
def ENV_NAME = "PROPERTIES_PATH"
if(!grails.config.location || !(grails.config.location instanceof List)) {
    grails.config.location = []
}
if(System.getenv(ENV_NAME)) {
    println "Including configuration file specified in environment: " + System.getenv(ENV_NAME);
    grails.config.location << "file:" + System.getenv(ENV_NAME)
    println(grails.config.location)

} else if(System.getProperty(ENV_NAME)) {
    println "Including configuration file specified on command line: " + System.getProperty(ENV_NAME);
    grails.config.location << "file:" + System.getProperty(ENV_NAME)
    println(grails.config.location)

} else {
    println "No external configuration file defined."
}
```

And I've created the file appName-config.groovy, in which I have the following:
    grails.plugin.elfinder.rootDir = "/home/francesco/docm_patients_doc/{patientcf}/"

At application startup, Ive the following exception:
    grails.plugin.elfinder.rootDir is not configured

**Comment by snimavat** [comment]
Well, its not the plugin issue. the configuration grails.plugin.elfinder.rootDir is not available when plugin is initialized. and this is causing the exception.

**Comment by francescodisciascio** [comment]
Ok. But the question is: is there a way to define rootDir path in external configuration file?because I don't want to leave that configuration into the config.groovy file.

**Comment by snimavat** [comment]
Ofcourse, the standard grails way of defining external config would work.Make sure that you have properly configured the external config location.

You may temporarily uninstall the plugin, and in your bootstrap, verify that the external config is available by inspecting grailsApplication.config

**Comment by francescodisciascio** [comment]
As you have suggested, I've uninstalled the plugin and added  a print of grailsApplication.config in Bootstrap.groovy file.
The print shows the following:
grailsApplication.config = ...config:[location:[file:/home/francesco/docm/medicalOfficeManager-config.groovy]...
I've tried to print grailsApplication.config.grails.plugin.elfinder.rootDir and it prints anything.
I've given 777 permission to both docm folder and configuration file, but nothing changes.
What am I missing?

**Comment by snimavat** [comment]
It's a configuration issue, not the plugin issue, you would be better ask it on mailing list.

**Comment by francescodisciascio** [comment]
Where is the mailing list?

**Comment by snimavat** [comment]
http://grails.org/Mailing+lists
